# Conditional Statements

There are some situations where we want to proceed with a task or perform an action dependent on whether a certain condition, or perhaps conditions, have been satified. For example, suppose we want to go on a walk outside if it is sunny. The action of going on a walk depends on whether it is sunny. In general, <i>conditional statements </i> are statements where an action or event occurs dependent on <i>if</i> a condition is true. We will investigate how to express these types of statements in python.

Conditional statements have the format of an if-then statement, <i>if</i> statement P, the hypothesis, occurs <i>then</i> statement Q, the conclusion, also occurs. How do we write this in code? We ultitize the <i>if</i> expression in python. The statement below will output the indented body <i> conclusion  </i> if <i>hypothesis </i> is true, otherwise if <i>hypothesis </i> is not True nothing is returned.
```python
if hypothesis:
    conclusion
```

In [4]:
import numpy as np
import pandas as pd

Perhaps we want to output whether a number is even. There is more than one method to code this! We could 
 - Extract the last digit and see if it equals 0,2,4,6, or 8.
 - Check the remainder when divided by 2 to see if it is 0.
 -  Take our input $n$ and check if $(-1)^n == 1$. 
 - Convert it to a binary number (a sequence of 0's and 1's that can uniquely represent each number) and check the last bit. 
 
The approach we will use is to check if the remainder when divided by 2 is 0. If the remainder is 0, then the input is divisible by 2 and thus even! Recall we use the <code> % </code> operator to compute the remainder.
We use the following <i> if </i> expression to write a function that tests if the input is even.

In [32]:
def test_even(input_number):
    if (input_number % 2) == 0:
        print(input_number, "is even")

If the input to this function is even, the string will be returned, otherwise this function returns nothing.

In [40]:
test_even(4)

4 is even


We can revise this function to also include information on odd integers. If we divide a number by 2 and get a remainder of 1, then the number is odd! Our revised function below takes an input integer then evaluates the first condition <i> Is the remainder 0? </i>, if so the corresponding string is printed. The next condition is then evaluated <i> Is the remainder 1? </i>, if so the corresponding string is printed. Notice that both conditions are always checked in the test_parity function. 

In [41]:
def test_parity(input_number):
    if (input_number % 2) == 0: 
        print(input_number, "is even")
    if (input_number % 2) == 1: 
        print(input_number, "is odd")        

In [43]:
test_parity(5)

5 is odd


In the case above where we have more than one conditional statement, it is computationally more efficient to utilize an elif statement. The format of an elif statement is
```python
if hypothesis_1:
    conclusion_1
elif hypothesis_2:
    conclusion_2
... 
elif hypothesis_n:
    conclusion_n
```
In an <i> elif </i> statement, once a condition is true the remaining condition or conditions are not evaulated.   
We revise the function test_parity to use an <i> elif </i> statement in a new function test_parity_revised.

In [1]:
def test_parity_revised(input_number):
    if (input_number % 2) == 0: 
        print(input_number, "is even")
    elif (input_number % 2) == 1: 
        print(input_number, "is odd")  

In [46]:
test_parity_revised(9)

9 is odd


Now our function can take any integer and output whether or not that value is even or odd. But what if our user enters the number 5.7? What if they enter a fraction or an irrational number?? We can make test_parity_revised more complete by indicting what to do in that case. 

Since we have a condition that checks all even numbers and a condition that checks all odd numbers, we want to group all other possibilities into one category - neither even nor odd. We can do this with the <i>else</i> statement. The <i> else </i> statement takes one of the following forms: We could have exactly two possible conclusions which leads to the format
```python
if hypothesis_1:
    conclusion_1
else:
    conclusion_2
```
    
or we could have $n+1$ conclusions for a chosen $n$ in which case we have the format
    
```python
if hypothesis_1:
    conclusion_1
elif hypothesis_2:
    conclusion_2
... 
elif hypothesis_n:
    conclusion_n
else:
    conclusion    
```    
    
Similar to an <i>elif </i> statement, once a condition is true in an <i> else </i> statement the remaining condition or conditions are not evaulated. Therefore when the <i>else </i> is reached in the code, it is the last option. At this point, all other conditions have been evaulated and none executed. Thus, there is no condition or hypothesis associated with the <i> else </i> statement. If it is reached in the code, the body of the <i>else </i> statement is executed.
    

    
We alter the function test_partity_revised to use an <i> else </i> statement in a new function test_parity_final.

In [ ]:
def test_parity_final(input_number):
    if (input_number % 2) == 0: 
        print(input_number, "is even")
    elif (input_number % 2) == 1: 
        print(input_number, "is odd")        
    else: 
        print(input_number, "is neither even nor odd") 

Comparing the output of this function to test_parity_revised, we see that the past functions cannot handle a decimal input like 5.7, whereas test_parity_final can!

In [48]:
test_parity_final(5)

5 is odd


In [49]:
test_parity_final(5.7)

5.7 is neither even nor odd


In [50]:
test_parity_revised(5.7)

A note of caution when using the <i> else </i> statement. Since the <i> else </i> statement is executed without checking a condition you want to be absolutely certain all desired possibilies are accounted for in the previous condition(s). For example if we change test_parity_revised as below to check if a number is even but assuming everything else must be odd we get an error when testing something like 5.7 in this function, as 5.7 is not odd.
```python 
def test_parity_revised(input_number):
    if (input_number % 2) == 0: 
        print(input_number, "is even")
    else: 
        print(input_number, "is odd")
```       

<code>test_parity_revised(5.7) </code>

<code>5.7 is odd </code>

# Example: six-sided die


We can use random selection in combination with conditional statements to investigate situations. For example, suppose we want to consider how often even versus odd numbers are rolled in 100 rolls of a fair six-sided die. 
We can illustrate this using the random choice function in addition to our parity function above.
<br>
First we create a six sided die by creating an array containing the numbers 1-6. When we randomly select a choice from this list we are simulating rolling a die. Repeating this 100 times gives us an array containing the outcomes of 100 tosses.

In [5]:
die = np.arange(1, 7)
die

array([1, 2, 3, 4, 5, 6])

In [6]:
results = np.random.choice(die,100)
results

array([5, 4, 1, 6, 1, 1, 6, 5, 5, 5, 6, 6, 3, 3, 1, 1, 6, 5, 2, 5, 3, 6,
       1, 6, 3, 2, 4, 3, 5, 1, 5, 2, 3, 5, 5, 6, 2, 2, 3, 6, 6, 1, 6, 4,
       4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 5, 2, 2, 2, 1, 6, 4, 5, 4, 6, 4, 4,
       1, 6, 5, 4, 3, 6, 3, 4, 2, 4, 6, 2, 2, 3, 3, 5, 3, 3, 1, 1, 6, 2,
       3, 4, 1, 4, 1, 3, 2, 4, 5, 1, 5, 5])

Our random roll generator outputs a number between 1 and 6, but we are only interested in if that number is even or odd. We cannot directly put an entire array through our parity function! We instead call np.vectorize which takes a function as input and returns a function that acts on an entire array as output, that is it allows for elementwise evaulation of the parity function!

Here we redefine our original parity function, then define a new function <i> vec_parity </i> that takes an array containing the roll results, that is an array of numbers 1-6, as input and produces an array denoting even or odd rolls. Note that in the function below we use an <i> if else </i> statement because we are assuming inputs are integer values from 1 to 6.

In [7]:
def parity(input_integer):
    if (input_integer % 2) == 0:
        return "even"
    else:
        return "odd"

    
vec_parity = np.vectorize(parity)
results = vec_parity(results)
results     

array(['odd', 'even', 'odd', 'even', 'odd', 'odd', 'even', 'odd', 'odd',
       'odd', 'even', 'even', 'odd', 'odd', 'odd', 'odd', 'even', 'odd',
       'even', 'odd', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'even',
       'odd', 'odd', 'odd', 'odd', 'even', 'odd', 'odd', 'odd', 'even',
       'even', 'even', 'odd', 'even', 'even', 'odd', 'even', 'even',
       'even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even', 'odd', 'even', 'even', 'even', 'odd', 'even',
       'even', 'odd', 'even', 'even', 'even', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'even', 'even',
       'even', 'even', 'even', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd',
       'odd', 'even', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'odd',
       'even', 'even', 'odd', 'odd', 'odd', 'odd'], dtype='<U4')

Our goal is to compare the total number of even rolls out of the total 100 rolls of the die. Recall we can count all the even rolls in the array by elemetwise comparing each result to 'even' and summing over the True instances.

In [8]:
total_even = sum(results == 'even')
total_even

53

Suppose we want to repeat this experiment a few times and record the results. We create a <i> results </i> array containing the total evens in the first 100 rolls and extend this list with each new experiment.

In [9]:
results = np.array([total_even]) 
results

array([53])

We first generate the 100 random rolls of the die using <code> np.random.choice(die,100)</code>. From this array, the vec_parity function will tell us which rolls were even and which rolls were odd. We sum over the even elements and append this to the current list. Recall the append call does not modify the original list, so the assignment is necessary.

In [10]:
results = np.append(results, sum(vec_parity(np.random.choice(die,100)) == 'even'))
results

array([53, 45])

We can run this experiment again!

In [11]:
results = np.append(results, sum(vec_parity(np.random.choice(die,100)) == 'even'))
results

array([53, 45, 63])

And again!

In [12]:
results = np.append(results, sum(vec_parity(np.random.choice(die,100)) == 'even'))
results

array([53, 45, 63, 60])

And again?

In [13]:
results = np.append(results, sum(vec_parity(np.random.choice(die,100)) == 'even'))
results

array([53, 45, 63, 60, 49])

Is there a more automated way? In the next section we explore how we can streamline this process of running an experiment multiple times.